name: ta
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  dropdown_search: ^0.6.1
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  flutter:
    sdk: flutter
  flutter_echarts: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  get: 4.6.5
  http: ^0.13.4
  intl: ^0.18.0
  lottie: ^2.3.2
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/splash/res/mipmap-xxxhdpi/ic_launcher.png"
  min_sdk_android: 21

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/roboto/Roboto-Regular.ttf

flutter:
  uses-material-design: true

  assets:
    - assets/img/foto.png
    - assets/img/logo.png
    - assets/img/logo-dengan-tulisan.png
